#!/bin/bash

set -eo pipefail

case "$1" in
  --pipeline|-p)
    open_pipeline=1
    shift
    ;;

  --help|-h)
    echo "Usage: $0 [options] [<remote>]" 1>&2
    echo 1>&2
    echo "Options:" 1>&2
    echo "  --pipeline, -p" 1>&2
    echo "    if set, tries to open the GitLab pipelines for HEAD" 1>&2
    exit 1
    ;;
esac

remote="$1"
if [[ ! "$remote" ]]; then
  remote="origin"
fi

remote_url=$(git remote get-url "$remote")
cleaned_url=$(echo "$remote_url" | sed 's/git@//; s/:/\//; s/.git$//')
url="https://$cleaned_url"

if [[ "$open_pipeline" ]]; then
  hash=$(git rev-parse HEAD)
  url="$url/commit/$hash/pipelines"
fi

open "$url"
