#!/bin/bash

set -eo pipefail


scripts=(git-open-web-ui git-submodule-update-and-commit)

for script in "${scripts[@]}"; do
  rm "/usr/local/bin/$script" 2>/dev/null || echo "$script is not installed"
done
